stages:
  - build
  - test
  - deploy
  
gcc-c++11-build-debug:
  stage: build
  script: "CI/ci-linux-build.sh gcc C++11 Debug"
  artifacts:
    paths:
      - build-*
  tags:
    - Linux

clang-c++11-build-debug:
  stage: build
  script: "CI/ci-linux-build.sh clang C++11 Debug"
  artifacts:
    paths:
      - build-*  
  tags:
    - Linux

gcc-c++98-build-debug:
  stage: build
  script: "CI/ci-linux-build.sh gcc C++98 Debug"
  artifacts:
    paths:
      - build-*  
  tags:
    - Linux

clang-c++98-build-debug:
  stage: build
  script: "CI/ci-linux-build.sh clang C++98 Debug"
  artifacts:
    paths:
      - build-*  
  tags: 
    - Linux
    
    
    
gcc-c++11-build-release:
  stage: build
  script: "CI/ci-linux-build.sh gcc C++11 Release"
  artifacts:
    paths:
      - build-*
  tags:
    - Linux

clang-c++11-build-release:
  stage: build
  script: "CI/ci-linux-build.sh clang C++11 Release"
  artifacts:
    paths:
      - build-*  
  tags:
    - Linux

gcc-c++98-build-release:
  stage: build
  script: "CI/ci-linux-build.sh gcc C++98 Release"
  artifacts:
    paths:
      - build-*  
  tags:
    - Linux

clang-c++98-build-release:
  stage: build
  script: "CI/ci-linux-build.sh clang C++98 Release"
  artifacts:
    paths:
      - build-*  
  tags: 
    - Linux    
    
    
    
    
    
    
    
gcc-c++11-test-debug:
  stage: test
  script: "CI/ci-linux-test.sh gcc C++11 Debug"
  dependencies: 
    - gcc-c++11-build-debug
  tags:
    - Linux

clang-c++11-test-debug:
  stage: test
  script: "CI/ci-linux-test.sh clang C++11 Debug"
  dependencies: 
    - clang-c++11-build-debug
  tags:
    - Linux

gcc-c++98-test-debug:
  stage: test
  script: "CI/ci-linux-test.sh gcc C++98 Debug"
  dependencies: 
    - gcc-c++98-build-debug
  tags:
    - Linux

clang-c++98-test-debug:
  stage: test
  script: "CI/ci-linux-test.sh clang C++98 Debug"
  dependencies: 
    - clang-c++98-build-debug
  tags: 
    - Linux    
    
gcc-c++11-test-release:
  stage: test
  script: "CI/ci-linux-test.sh gcc C++11 Release"
  dependencies: 
    - gcc-c++11-build-release
  tags:
    - Linux

clang-c++11-test-release:
  stage: test
  script: "CI/ci-linux-test.sh clang C++11 Release"
  dependencies: 
    - clang-c++11-build-release
  tags:
    - Linux

gcc-c++98-test-release:
  stage: test
  script: "CI/ci-linux-test.sh gcc C++98 Release"
  dependencies: 
    - gcc-c++98-build-release
  tags:
    - Linux

clang-c++98-test-release:
  stage: test
  script: "CI/ci-linux-test.sh clang C++98 Release"
  dependencies: 
    - clang-c++98-build-release
  tags: 
    - Linux        

    
    
    
    
    
macos-c++11:
  script: "CI/ci-mac.sh C++11"
  tags:
    - Apple
  artifacts:
    paths:
      - build-release-cpp11/*.dmg
      - build-release-cpp11/*.tar.gz

macos-c++98:
  script: "CI/ci-mac.sh C++98"
  tags:
    - Apple
  artifacts:
    paths:
      - build-release-cpp98/*.dmg
      - build-release-cpp98/*.tar.gz

cppcheck:
  script: "CI/ci-cppcheck.sh"
  tags:
    - Linux
  artifacts:
    paths:
      - cppcheck.log
