stages:
  - build
  - test
  - deploy
  
gcc-c++11-build-debug:
  stage: build
  script: "CI/ci-linux-build.sh gcc C++11 Debug"
  artifacts:
    paths:
      - build-*
  tags:
    - Linux

clang-c++11-build-debug:
  stage: build
  script: "CI/ci-linux-build.sh clang C++11 Debug"
  artifacts:
    paths:
      - build-*  
  tags:
    - Linux

gcc-c++98-build-debug:
  stage: build
  script: "CI/ci-linux-build.sh gcc C++98 Debug"
  artifacts:
    paths:
      - build-*  
  tags:
    - Linux

clang-c++98-build-debug:
  stage: build
  script: "CI/ci-linux-build.sh clang C++98 Debug"
  artifacts:
    paths:
      - build-*  
  tags: 
    - Linux
    
    
    
gcc-c++11-build-release:
  stage: build
  script: "CI/ci-linux-build.sh gcc C++11 Release"
  artifacts:
    paths:
      - build-*
  tags:
    - Linux

clang-c++11-build-release:
  stage: build
  script: "CI/ci-linux-build.sh clang C++11 Release"
  artifacts:
    paths:
      - build-*  
  tags:
    - Linux

gcc-c++98-build-release:
  stage: build
  script: "CI/ci-linux-build.sh gcc C++98 Release"
  artifacts:
    paths:
      - build-*  
  tags:
    - Linux

clang-c++98-build-release:
  stage: build
  script: "CI/ci-linux-build.sh clang C++98 Release"
  artifacts:
    paths:
      - build-*  
  tags: 
    - Linux    
    
    
    
    
    
    
    
gcc-c++11-test-debug:
  stage: test
  script: "CI/ci-linux-test.sh gcc C++11 Debug"
  dependencies: 
    - gcc-c++11-build-debug
  tags:
    - Linux

clang-c++11-test-debug:
  stage: test
  script: "CI/ci-linux-test.sh clang C++11 Debug"
  dependencies: 
    - clang-c++11-build-debug
  tags:
    - Linux

gcc-c++98-test-debug:
  stage: test
  script: "CI/ci-linux-test.sh gcc C++98 Debug"
  dependencies: 
    - gcc-c++98-build-debug
  tags:
    - Linux

clang-c++98-test-debug:
  stage: test
  script: "CI/ci-linux-test.sh clang C++98 Debug"
  dependencies: 
    - clang-c++98-build-debug
  tags: 
    - Linux    
    
gcc-c++11-test-release:
  stage: test
  script: "CI/ci-linux-test.sh gcc C++11 Release"
  dependencies: 
    - gcc-c++11-build-release
  tags:
    - Linux

clang-c++11-test-release:
  stage: test
  script: "CI/ci-linux-test.sh clang C++11 Release"
  dependencies: 
    - clang-c++11-build-release
  tags:
    - Linux

gcc-c++98-test-release:
  stage: test
  script: "CI/ci-linux-test.sh gcc C++98 Release"
  dependencies: 
    - gcc-c++98-build-release
  tags:
    - Linux

clang-c++98-test-release:
  stage: test
  script: "CI/ci-linux-test.sh clang C++98 Release"
  dependencies: 
    - clang-c++98-build-release
  tags: 
    - Linux        

    
    
macos-c++11-build-release:
  stage: build
  script: "CI/ci-mac-build.sh C++11 Release"
  tags:
    - Apple
  artifacts:
    paths:
      - build-*

macos-c++98-build-release:
  stage: build
  script: "CI/ci-mac-build.sh C++98 Release"
  tags:
    - Apple
  artifacts:
    paths:
      - build-* 
    
macos-c++11-build-debug:
  stage: build
  script: "CI/ci-mac-build.sh C++11 Debug"
  tags:
    - Apple
  artifacts:
    paths:
      - build-*

macos-c++98-build-debug:
  stage: build
  script: "CI/ci-mac-build.sh C++98 Debug"
  tags:
    - Apple
  artifacts:
    paths:
      - build-*

      
macos-c++11-test-release:
  stage: test
  script: "CI/ci-mac-test.sh C++11 Release"
  dependencies:
    - macos-c++11-build-release
  tags:
    - Apple

macos-c++98-test-release:
  stage: test
  script: "CI/ci-mac-test.sh C++98 Release"
  dependencies:
    - macos-c++98-build-release
  tags:
    - Apple
    
macos-c++11-test-debug:
  stage: test
  script: "CI/ci-mac-test.sh C++11 Debug"
  dependencies:
    - macos-c++11-build-debug
  tags:
    - Apple

macos-c++98-test-debug:
  stage: test
  script: "CI/ci-mac-test.sh C++98 Debug"
  dependencies:
    - macos-c++98-build-debug
  tags:
    - Apple
   
   
   
   
macos-c++11-deploy:
  stage: deploy
  script: "CI/ci-mac-deploy.sh C++11"
  dependencies:
    - macos-c++11-build-release
    - macos-c++11-build-debug   
  artifacts:
    paths:
      - build-release-cpp11/*.dmg
      - build-release-cpp11/*.tar.gz
  tags:
    - Apple

macos-c++98-deploy:
  stage: deploy
  script: "CI/ci-mac-deploy.sh C++98"
  dependencies:
    - macos-c++98-build-release
    - macos-c++98-build-debug      
  artifacts:
    paths:
      - build-release-cpp98/*.dmg
      - build-release-cpp98/*.tar.gz    
  tags:
    - Apple      
     
     
      
   
      

cppcheck:
  script: "CI/ci-cppcheck.sh"
  tags:
    - Linux
  artifacts:
    paths:
      - cppcheck.log
